name: ttyloop

on:
  push:
    branches:
      # Local policy requires staging checks before pushing to main.
      - pkg-staging
    paths:
      - pkgs/ttyloop.nix
      - flake.lock

jobs:
  ttyloop:
    uses: ./.github/workflows/build-nix.yaml
    with:
      build_target: ".#ttyloop"
    secrets:
      cachix_auth_token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
